### ISSUE TITLE
writeup api section

### ISSUE THREAD

**Issue by snowmang1** [baserrato/devops-custom-provider#21]
### Tasks
- [x] includes explanation of api
- [x] demo of api
- - revise benny's script to be more understandable
- - comment benny's script
- - add man to benny's script to help with experimental use
- [x] explanation of structures within api

**Comment by snowmang1** [comment]
Steven finished

**Comment by snowmang1** [comment]
@MinecraftSt3v3 ☝️ this is what I wanted. This tells everyone that you have finished the task so if you want to use this same branch to resolve multiple tickets this is how it is done.
