### ISSUE TITLE
writeup engineer section

### ISSUE THREAD

**Issue by snowmang1** [baserrato/devops-custom-provider#23]
### Tasks
- [x] #21 
- [x] explanation of engineer resource
- [x] demo of engineer components
- - gh perma links to api repo file containing engineer resource description
- [x] include some tests to assure engineer resource is built correctly
- - tests DO NOT have to be terraform tests
- - - they can be logic tests, or any other kind of test
- - - the tests should just prove to them that the structures are correct
