### ISSUE TITLE
Test init process

### ISSUE THREAD

**Issue by snowmang1** [baserrato/devops-custom-provider#59]
### Tasks
- [x] go through initial provider install
- [x] go through api install
- [x] test api makefile
- [x] is provider makefile required in docs (yes/no)

### Notes
- Add Makefile to Excersise 1, 6.1.4
- Add further Deliverables to 6.1.4 to cover the Makefile
